{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "test_namespace.model.Person",
      "children" : [ {
        "name" : "replica from replica",
        "uid" : "e7824b084950bcb7",
        "parentUid" : "922a167c12dab399705471de13b678b7",
        "status" : "broken",
        "time" : {
          "start" : 1630913753604,
          "stop" : 1630913979473,
          "duration" : 225869
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "None", "jdk8", "Linux", "linux/amd64", "normal" ]
      } ],
      "uid" : "922a167c12dab399705471de13b678b7"
    }, {
      "name" : "dataclay.exceptions.exceptions.DataClayException: b'\\n--------------------------------------------------------------------------------------------------------------------------------------------------\\nError Stack: \\n--------------------------------------------------------------------------------------------------------------------------------------------------\\nServer Traceback (most recent call last):\\n  File \"/home/dataclayusr/dataclay/dataclay_venv/lib/python3.6/site-packages/dataClay-2.7-py3.6.egg/dataclay/communication/grpc/server/ExecutionEnvironmentService.py\", line 130, in makePersistent\\n    self.execution_environment.make_persistent(session_id, objects_to_persist)\\n\\n--------------------------------------------------------------------------------------------------------------------------------------------------'\n",
      "children" : [ {
        "name" : "replica an object",
        "uid" : "ad945172b0bd72a2",
        "parentUid" : "ac81b4ca1c356971797067a5a7e53d9f",
        "status" : "broken",
        "time" : {
          "start" : 1631172288921,
          "stop" : 1631172452405,
          "duration" : 163484
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "None", "py36", "Linux", "linux/amd64", "normal" ]
      } ],
      "uid" : "ac81b4ca1c356971797067a5a7e53d9f"
    }, {
      "name" : "dataclay.exceptions.exceptions.DataClayException: b'\\n--------------------------------------------------------------------------------------------------------------------------------------------------\\nError Stack: \\n--------------------------------------------------------------------------------------------------------------------------------------------------\\nServer Traceback (most recent call last):\\n  File \"/home/dataclayusr/dataclay/dataclay_venv/lib/python3.8/site-packages/dataClay-2.7-py3.8.egg/dataclay/communication/grpc/server/ExecutionEnvironmentService.py\", line 328, in newReplica\\n    result = self.execution_environment.new_replica(Utils.get_id(request.sessionID),\\n\\n--------------------------------------------------------------------------------------------------------------------------------------------------'\n",
      "children" : [ {
        "name" : "replica from replica",
        "uid" : "a3aba905590155e7",
        "parentUid" : "bacde1224e0b58f2e606c65e00f793cf",
        "status" : "broken",
        "time" : {
          "start" : 1631174773189,
          "stop" : 1631174897714,
          "duration" : 124525
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ "None", "py38", "Linux", "linux/amd64", "normal" ]
      } ],
      "uid" : "bacde1224e0b58f2e606c65e00f793cf"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ],
  "name" : "categories"
}